#####################################################################
#                                                                   #
# Script:  compose.yaml                                             #
#                                                                   #
# Purpose: Docker compose definition for nova-db                    #
#                                                                   #
# Date:    11th May 2025                                            #
#                                                                   #
# Author:  nova admin <admin@nova>                                  #
#                                                                   #
#####################################################################

services:
  nova-db:
    image: 'ghcr.io/nova-eco/nova-db:latest'
    env_file:
      - path: ./.env
        required: true
    environment:
      MARIADB_DATABASE: ${NOVA_DB__NAME}
      MARIADB_ROOT_PASSWORD: ${NOVA_DB__USER__ROOT_PASS}
      MARIADB_USER: ${NOVA_DB__USER__STD}
      MARIADB_PASSWORD: ${NOVA_DB__USER__STD_PASS}
    healthcheck:
      interval: 10s
      start_period: 30s
      test: ['CMD', 'healthcheck.sh', '--connect', '--innodb_initialized']
      timeout: 5s
    networks:
      - '${NOVA_DB__NETWORK}'
    ports:
      - '127.0.0.1:${NOVA_DB__PORT}:3306'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          memory: 512M

  nova-api:
    image: 'ghcr.io/nova-eco/nova-api:latest'
    env_file:
      - path: ./.env
        required: true
    environment:
      NOVA_API__AUTHOR: '${NOVA_API__AUTHOR}'
      NOVA_API__NAME: '${NOVA_API__NAME}'
      NOVA_API__PORT: '${NOVA_API__PORT}'
      API_NAME: '${API_NAME}'
      API_PORT: '${API_PORT}'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:${API_PORT}/healthcheck']
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - '${NOVA__NETWORK}'
    ports:
      - '127.0.0.1:${API_PORT}:${API_PORT}'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          memory: 512M

networks:
  nova-network:
    driver: bridge
    internal: false
    name: ${NOVA_DB__NETWORK}
