#####################################################################
#                                                                   #
# Script:  compose.yaml                                             #
#                                                                   #
# Purpose: Docker compose definition for nova-db                    #
#                                                                   #
# Date:    11th May 2025                                            #
#                                                                   #
# Author:  nova admin <admin@nova>                                  #
#                                                                   #
#####################################################################

services:
  nova-db:
    build:
      context: ../nova-db
      dockerfile: Dockerfile
      args:
        NOVA_DB__AUTHOR: ${NOVA_DB__AUTHOR}
        NOVA_DB__SQL__FILE: ${NOVA_DB__SQL__FILE}
        NOVA_DB__SQL__PATH: ${NOVA_DB__SQL__PATH}
        MARIADB_DATABASE: ${NOVA_DB__NAME}
        MARIADB_ROOT_PASSWORD: ${NOVA_DB__USER__ROOT_PASS}
        MARIADB_USER: ${NOVA_DB__USER__STD}
        MARIADB_PASSWORD: ${NOVA_DB__USER__STD_PASS}
    image: 'ghcr.io/nova-eco/nova-db:latest'
    env_file:
      - path: ./.env
        required: true
    environment:
      MARIADB_DATABASE: ${NOVA_DB__NAME}
      MARIADB_ROOT_PASSWORD: ${NOVA_DB__USER__ROOT_PASS}
      MARIADB_USER: ${NOVA_DB__USER__STD}
      MARIADB_PASSWORD: ${NOVA_DB__USER__STD_PASS}
    healthcheck:
      interval: 10s
      start_period: 30s
      test: ['CMD', 'mariadb', '-uroot', '-ppass', '-e', 'SELECT 1']
      timeout: 5s
    networks:
      - '${NOVA_DB__NETWORK}'
    ports:
      - '${NOVA_DB__PORT}:${NOVA_DB__PORT}'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          memory: 512M

  nova-api:
    build:
      context: ../nova-api
      dockerfile: Dockerfile
      args:
        NOVA_API__AUTHOR: ${NOVA_API__AUTHOR}
        NOVA_API__NAME: ${NOVA_API__NAME}
        NOVA_API__PORT: ${NOVA_API__PORT}
        API_NAME: ${API_NAME}
        API_PORT: ${API_PORT}
    image: 'ghcr.io/nova-eco/nova-api:latest'
    depends_on:
      nova-db:
        condition: service_healthy
    env_file:
      - path: ./.env
        required: true
    environment:
      NOVA_API__AUTHOR: '${NOVA_API__AUTHOR}'
      NOVA_API__NAME: '${NOVA_API__NAME}'
      NOVA_API__PORT: '${NOVA_API__PORT}'
      API_NAME: '${API_NAME}'
      API_PORT: '${API_PORT}'
      DB_HOST: '${DB_HOST}'
      DB_USER: '${DB_USER}'
      DB_PASSWORD: '${DB_PASSWORD}'
      DB_NAME: '${DB_NAME}'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:${API_PORT}/healthcheck']
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - '${NOVA__NETWORK}'
    ports:
      - '${API_PORT}:${API_PORT}'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          memory: 512M

networks:
  nova-network:
    driver: bridge
    internal: false
    name: ${NOVA_DB__NETWORK}
