#####################################################################
#                                                                   #
# Script:  compose.yaml                                             #
#                                                                   #
# Purpose: Docker compose definition for nova-db                    #
#                                                                   #
# Date:    11th May 2025                                            #
#                                                                   #
# Author:  nova admin <admin@nova>                                  #
#                                                                   #
#####################################################################

services:
  nova-db:
    build:
      context: ../nova-db
      dockerfile: Dockerfile
      args:
        NOVA_DB_AUTHOR: ${NOVA_DB_AUTHOR}
        NOVA_DB_SQL_FILE: ${NOVA_DB_SQL_FILE}
        NOVA_DB_SQL_PATH: ${NOVA_DB_SQL_PATH}
        MARIADB_DATABASE: ${NOVA_DB_NAME}
        MARIADB_ROOT_PASSWORD: ${NOVA_DB_USER_ROOT_PASS}
        MARIADB_USER: ${NOVA_DB_USER_STD}
        MARIADB_PASSWORD: ${NOVA_DB_USER_STD_PASS}
    image: 'ghcr.io/nova-eco/nova-db:latest'
    env_file:
      - path: ./.env
        required: true
    environment:
      MARIADB_DATABASE: ${NOVA_DB_NAME}
      MARIADB_ROOT_PASSWORD: ${NOVA_DB_USER_ROOT_PASS}
      MARIADB_USER: ${NOVA_DB_USER_STD}
      MARIADB_PASSWORD: ${NOVA_DB_USER_STD_PASS}
    healthcheck:
      interval: 10s
      start_period: 30s
      test: ['CMD', 'mariadb', '-uroot', '-ppass', '-e', 'SELECT 1']
      timeout: 5s
    networks:
      - '${NOVA_DB_NETWORK}'
    ports:
      - '${NOVA_DB_PORT}:${NOVA_DB_PORT}'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          memory: 512M

  nova-api:
    build:
      context: ../nova-api
      dockerfile: Dockerfile
      args:
        NOVA_API_AUTHOR: ${NOVA_API_AUTHOR}
        NOVA_API_NAME: ${NOVA_API_NAME}
        NOVA_API_PORT: ${NOVA_API_PORT}
        NOVA_API_SERVICE_NAME: ${NOVA_API_SERVICE_NAME}
    image: 'ghcr.io/nova-eco/nova-api:latest'
    depends_on:
      nova-db:
        condition: service_healthy
    env_file:
      - path: ./.env
        required: true
    environment:
      NOVA_API_AUTHOR: '${NOVA_API_AUTHOR}'
      NOVA_API_NAME: '${NOVA_API_NAME}'
      NOVA_API_PORT: '${NOVA_API_PORT}'
      NOVA_API_SERVICE_NAME: '${NOVA_API_SERVICE_NAME}'
      NOVA_API_DB_HOST: '${NOVA_API_DB_HOST}'
      NOVA_API_DB_USER: '${NOVA_API_DB_USER}'
      NOVA_API_DB_PASSWORD: '${NOVA_API_DB_PASSWORD}'
      NOVA_API_DB_NAME: '${NOVA_API_DB_NAME}'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:${NOVA_API_PORT}/healthcheck']
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - '${NOVA_DB_NETWORK}'
    ports:
      - '${NOVA_API_PORT}:${NOVA_API_PORT}'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          memory: 512M

  nova-web:
    build:
      context: ../nova-web
      dockerfile: Dockerfile
      args:
        NOVA_WEB_API_HOST: ${NOVA_WEB_API_HOST}
        NOVA_WEB_API_PORT: ${NOVA_WEB_API_PORT}
        NOVA_WEB_API_PROTOCOL: ${NOVA_WEB_API_PROTOCOL}
        NOVA_WEB_AUTHOR: ${NOVA_WEB_AUTHOR}
        NOVA_WEB_HOST: ${NOVA_WEB_HOST}
        NOVA_WEB_NAME: ${NOVA_WEB_NAME}
        NOVA_WEB_NETWORK: ${NOVA_WEB_NETWORK}
        NOVA_WEB_PORT: ${NOVA_WEB_PORT}
    image: 'ghcr.io/nova-eco/nova-web:latest'
    depends_on:
      nova-db:
        condition: service_healthy
    env_file:
      - path: ./.env
        required: true
    environment:
      NOVA_WEB_API_HOST: '${NOVA_WEB_API_HOST}'
      NOVA_WEB_API_PORT: '${NOVA_WEB_API_PORT}'
      NOVA_WEB_API_PROTOCOL: '${NOVA_WEB_API_PROTOCOL}'
      NOVA_WEB_AUTHOR: '${NOVA_WEB_AUTHOR}'
      NOVA_WEB_HOST: '${NOVA_WEB_HOST}'
      NOVA_WEB_NAME: '${NOVA_WEB_NAME}'
      NOVA_WEB_NETWORK: '${NOVA_WEB_NETWORK}'
      NOVA_WEB_PORT: '${NOVA_WEB_PORT}'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:${NOVA_WEB_PORT}/healthcheck']
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - '${NOVA_WEB_NETWORK}'
    ports:
      - '${NOVA_WEB_PORT}:${NOVA_WEB_PORT}'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          memory: 512M

networks:
  nova-network:
    driver: bridge
    internal: false
    name: ${NOVA_DB_NETWORK}
